name: Slack package version notification
on:
  push:
    branches-ignore:
      - 'releases/**-alpha'

jobs:
  notify:
    name: Notify slack
    runs-on: ubuntu-latest
    steps:

      - name: Send Slack notification
        uses: abinoda/slack-action@master
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          args: '{
          \"channel\":\"${{ secrets.SLACK_CHANNEL_ID}}\",
          \"blocks\": [
                  {
                      \"type\": \"header\",
                      \"text\": {
                          \"type\": \"plain_text\",
                          \"text\": \"My awesome published package\",
                          \"emoji\": true
                      }
                  }
              ]
          }'
