name: Slack package version notification 2.1

on:
  registry_package:
    types: [published, updated]

jobs:
  notify:
    name: Notify slack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
      - run: echo $SHA
        env:
          SHA: ${{ steps.short-sha.outputs.sha }}
      #START SECTION
      - name: Make Request
        id: myRequest
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://api.vercel.com/v6/deployments"
          method: 'GET'
          customHeaders: '{"Authorization": "Bearer ${{ secrets.VERCEL_TOKEN}}"}'
      - name: Show Response
        run: |
          echo ${{ steps.myRequest.outputs.response.deployments[0].meta.url }}
      #END SECTION
      - name: Send Slack notification
        uses: abinoda/slack-action@master
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          args: '{\"channel\":\"${{ secrets.SLACK_CHANNEL_ID}}\",\"blocks\":[{\"type\":\"header\",\"text\":{\"type\":\"plain_text\",\"text\":\"New package published\"}},{\"type\":\"divider\"},{\"type\":\"context\",\"elements\":[{\"type\":\"mrkdwn\",\"text\":\":package: Name: @playsportsgroup\/${{ steps.short-sha.outputs.sha }} \n\"},{\"type\":\"mrkdwn\",\"text\":\":rocket: Version: ${{ github.event.registry_package.package_version.version }}\"}]},{\"type\":\"actions\",\"block_id\":\"packageLink\",\"elements\":[{\"type\":\"button\",\"text\":{\"type\":\"plain_text\",\"text\":\"Visit the package\"},\"style\":\"primary\",\"action_id\":\"button\",\"url\":\"${{ github.event.registry_package.html_url }}\"}]}]}'