name: Slack package version notification 2.1

on:
  registry_package:
    types: [published, updated]

jobs:
  notify:
    name: Notify slack
    runs-on: ubuntu-latest
    steps:

      - name: Debug
        run: |
          echo ${github.event.registry_package}

      - name: Send Slack notification
        uses: abinoda/slack-action@master
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          args: '{\"channel\":\"${{ secrets.SLACK_CHANNEL_ID}}\", \"text\":\"Hello world\"}'
